// 文件职责：用 esbuild 把内置扩展运行时入口 src/index.js 打包为单文件 IIFE，产出 GearMac//Resources/RaycastRuntime.generated.js。
// 分层：构建脚本；产物需重新生成并提交入库，编译 GearMac 时不依赖 Node。
//
//   pnpm install && node gen-enums.mjs && node build.mjs
//
// 产物会被提交入库（与 EmojiData.generated.swift 同理），因此编译 GearMac 时不需要 Node。

import { build } from "esbuild";
import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const outFile = resolve("../../GearMac//Resources/RaycastRuntime.generated.js");
const dev = process.argv.includes("--dev");

mkdirSync(dirname(outFile), { recursive: true });

const result = await build({
  entryPoints: ["src/index.js"],
  bundle: true,
  format: "iife",
  platform: "neutral",
  // macOS 26 上的 JavaScriptCore 已完全支持现代语法，无需降级编译。
  target: ["es2022"],
  minify: !dev,
  sourcemap: false,
  legalComments: "none",
  write: false,
  define: {
    "process.env.NODE_ENV": dev ? '"development"' : '"production"',
    __DEV__: dev ? "true" : "false",
  },
  banner: {
    js: "// Generated by Tools/raycast-runtime — do not edit. Regenerate with `node build.mjs`.",
  },
});

for (const warning of result.warnings) console.warn(warning.text);

const [output] = result.outputFiles;
// `__gearmacCompile` 必须在*全局*作用域中编译，使被它求值的扩展包看不到运行时自身的模块局部变量。
// 该函数由 Swift 安装，不在这里定义。
writeFileSync(outFile, output.text);

const { size } = statSync(outFile);
console.log(`RaycastRuntime.generated.js — ${(size / 1024).toFixed(1)} KB${dev ? " (dev)" : ""}`);
