// 文件职责：从 @raycast/api 的真实类型定义生成 src/api/enums.generated.js，使 Icon / Color / Toast.Style / Keyboard 等携带扩展用来比较的准确字符串值。
// 分层：代码生成脚本；升级 @raycast/api 依赖后运行，随后执行 `node build.mjs`。
//
//   node gen-enums.mjs
//
// 在升级 @raycast/api devDependency 后运行，然后执行 `node build.mjs`。

import { readFileSync, writeFileSync } from "node:fs";

const dts = readFileSync("node_modules/@raycast/api/types/index.d.ts", "utf8").replace(/\r\n/g, "\n");

/// 遍历声明文件，按花括号深度跟踪 `namespace`/`enum` 的嵌套，收集每个枚举成员。
/// 带命名空间的枚举以点分路径（`Image.Mask`）作为键；仅重新绑定顶层枚举的命名空间
/// （`const Style: typeof ToastStyle_2;`）会被记录为别名。
function collectEnums(source) {
  const lines = source.split("\n");
  const scopes = [];
  const enums = new Map();
  const aliases = new Map();
  let depth = 0;
  let current = null;

  for (const line of lines) {
    const namespaceMatch = /^\s*(?:export\s+)?declare\s+namespace\s+([A-Za-z0-9_]+)\s*\{/.exec(line);
    const enumMatch = /^\s*(?:export\s+)?(?:declare\s+)?enum\s+([A-Za-z0-9_]+)\s*\{/.exec(line);
    const aliasMatch = /^\s*(?:export\s+)?const\s+([A-Za-z0-9_]+)\s*:\s*typeof\s+([A-Za-z0-9_.]+)\s*;/.exec(line);

    if (!current && enumMatch) {
      const path = [...scopes.map((scope) => scope.name), enumMatch[1]].join(".");
      current = { path, members: [], startDepth: depth };
      enums.set(path, current.members);
      depth += 1;
      continue;
    }
    if (!current && namespaceMatch) {
      scopes.push({ name: namespaceMatch[1], depth });
      depth += 1;
      continue;
    }
    if (!current && aliasMatch && scopes.length) {
      aliases.set([...scopes.map((scope) => scope.name), aliasMatch[1]].join("."), aliasMatch[2]);
      continue;
    }

    if (current) {
      const member = /^\s*([A-Za-z0-9_]+)\s*=\s*"([^"]*)"/.exec(line);
      if (member) current.members.push([member[1], member[2]]);
    }

    for (const char of line) {
      if (char === "{") depth += 1;
      else if (char === "}") {
        depth -= 1;
        if (current && depth === current.startDepth) current = null;
        while (scopes.length && depth <= scopes[scopes.length - 1].depth) scopes.pop();
      }
    }
  }
  return { enums, aliases };
}

// `Foo_2` 这类重复项是声明文件用来区分同一公开枚举的 List/Grid 变体、以及把带命名空间的枚举提升到顶层的手段。
const publicPath = (path) => path.replace(/_\d+(\.|$)/g, "$1");

const { enums: rawEnums, aliases } = collectEnums(dts);
const enums = new Map();
for (const [path, members] of rawEnums) {
  if (!members.length) continue;
  const clean = publicPath(path);
  if (!enums.has(clean)) enums.set(clean, members);
}
for (const [path, target] of aliases) {
  const members = enums.get(publicPath(target));
  if (members && !enums.has(path)) enums.set(path, members);
}

// 把枚举成员列表序列化为 `Object.freeze({...})` 形式的字面量源码。
function literal(members) {
  return `Object.freeze({\n${members.map(([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`).join("\n")}\n})`;
}

const lines = [
  "// Generated by gen-enums.mjs from @raycast/api's type definitions — do not edit by hand.",
  "",
];

const roots = [...enums.keys()].filter((path) => !path.includes("."));
for (const path of roots) {
  lines.push(`export const ${path} = ${literal(enums.get(path))};`, "");
}

const nested = {};
for (const [path, members] of enums) {
  if (!path.includes(".")) continue;
  const [scope, ...rest] = path.split(".");
  nested[scope] = nested[scope] || [];
  nested[scope].push([rest.join("."), members]);
}
lines.push("export const nestedEnums = {");
for (const scope of Object.keys(nested).sort()) {
  lines.push(`  ${JSON.stringify(scope)}: {`);
  for (const [name, members] of nested[scope]) {
    lines.push(`    ${JSON.stringify(name)}: ${literal(members).replace(/\n/g, "\n    ")},`);
  }
  lines.push("  },");
}
lines.push("};", "");

writeFileSync("src/api/enums.generated.js", lines.join("\n"));

const total = [...enums.values()].reduce((sum, members) => sum + members.length, 0);
console.log(`enums.generated.js: ${enums.size} enums, ${total} members`);
console.log([...enums.keys()].join(", "));
