// 文件职责：枚举 settings.json 的全部键（SettingsFileKey），rawValue 即文件中的点号路径。
// 分层：Model；rawValue 为显式字符串，重命名 case 不会改变文件里的键名。
import Foundation

/// settings.json 包含的每个键，按文件列出它们的顺序排列；rawValue 即其路径。
enum SettingsFileKey: String, CaseIterable, Sendable {
    // 显式写出，因此重命名 case 永远不会改变用户文件里的键名。
    case launcherShortcut = "general.launcherShortcut"
    case showInMenuBar = "general.showInMenuBar"
    case language = "general.language"
    case automaticallyCheckForUpdates = "general.automaticallyCheckForUpdates"
    case popToRootTimeout = "general.popToRootSeconds"
    case escapeKeyBehavior = "general.escapeKeyBehavior"
    case autoSwitchInputSource = "general.autoSwitchInputSource"
    case supportReminders = "general.supportReminders"
    case appearance = "appearance.theme"
    case interfaceSize = "appearance.interfaceSize"
    case compactMode = "appearance.compactMode"
    case showFavoritesInCompactMode = "appearance.showFavoritesInCompactMode"
    case openOnCursorScreen = "appearance.followCursorAcrossDisplays"
    case paletteDraggable = "appearance.dragToReposition"
    case hyperKey = "hyperKey.key"
    case hyperKeyIncludesShift = "hyperKey.includesShift"
    case hyperKeyQuickPress = "hyperKey.quickPress"
    case calcNumberStyle = "calculator.numberStyle"
    case launcherShowsSuggestions = "search.showsSuggestions"
    case rootSearchSensitivity = "search.sensitivity"
    case applicationsEnabled = "applications.enabled"
    case searchScopes = "applications.searchScopes"
    case applications = "applications.apps"
    case systemSettingsEnabled = "systemSettings.enabled"
    case systemSettings = "systemSettings.panes"
    case systemActionsEnabled = "systemActions.enabled"
    case systemActions = "systemActions.actions"
    case builtInCommandsEnabled = "commands.builtInEnabled"
    case builtInCommands = "commands.builtIn"
    case customCommandsEnabled = "commands.enabled"
    case customCommandsShowInLauncher = "commands.showInLauncher"
    case quicklinksEnabled = "quicklinks.enabled"
    case quicklinksShowInLauncher = "quicklinks.showInLauncher"
    case quicklinkOpensNewWindow = "quicklinks.opensNewWindow"
    case quicklinkSelectionFallback = "quicklinks.selectionFallback"
    case quicklinkConfirmsBeforeDelete = "quicklinks.confirmsBeforeDelete"
    case quicklinkCommands = "quicklinks.commands"
    case appleShortcutsEnabled = "appleShortcuts.enabled"
    case aiEnabled = "ai.enabled"
    case aiWebSearch = "ai.webSearch"
    case aiSystemPrompt = "ai.systemPrompt"
    case aiSystemPromptEnabled = "ai.systemPromptEnabled"
    case aiRetention = "ai.retentionDays"
    case aiOpensTo = "ai.opensTo"
    case aiNewChatAfter = "ai.newChatAfterMinutes"
    case aiToolRounds = "ai.toolRounds"
    case aiCommands = "ai.commands"
    case quickActionLanguage = "quickActions.targetLanguage"
    case quickActionCommands = "quickActions.commands"
    case dictationMode = "dictation.mode"
    case dictationShortcut = "dictation.shortcut"
    case dictationModel = "dictation.model"
    case dictationMicrophone = "dictation.microphone"
    case dictationDestination = "dictation.destination"
    case dictationAdaptsCapitalization = "dictation.adaptsCapitalization"
    case dictationIdleRelease = "dictation.releaseAfterMinutes"
    case dictationLanguage = "dictation.language"
    case fileSearchEnabled = "fileSearch.enabled"
    case fileSearchScopes = "fileSearch.scopes"
    case fileSearchIgnorePatterns = "fileSearch.ignorePatterns"
    case fileSearchCommands = "fileSearch.commands"
    case notesEnabled = "notes.enabled"
    case notesRendersMarkdown = "notes.rendersMarkdown"
    case notesShowsFormattingBar = "notes.showsFormattingBar"
    case notesFolder = "notes.folder"
    case notesCommands = "notes.commands"
    case snippetsShowInLauncher = "snippets.showInLauncher"
    case snippetsFolder = "snippets.folder"
    case snippetsCommands = "snippets.commands"
    case navigationEnabled = "navigation.enabled"
    case menuSearchShowsAppleMenu = "navigation.menuSearchShowsAppleMenu"
    case menuSearchDisabledApps = "navigation.menuSearchDisabledApps"
    case navigationCommands = "navigation.commands"
    case windowManagementEnabled = "windowManagement.enabled"
    case windowManagementShowInLauncher = "windowManagement.showInLauncher"
    case windowGap = "windowManagement.gap"
    case windowCycle = "windowManagement.cycle"
    case windowLayoutsShowInLauncher = "windowManagement.layoutsShowInLauncher"
    case windowRoomsShowInLauncher = "windowManagement.roomsShowInLauncher"
    case windowShortcuts = "windowManagement.shortcuts"
    case windowAliases = "windowManagement.aliases"
    case customWindowSizes = "windowManagement.customSizes"
    case windowLayouts = "windowManagement.layouts"
    case windowRooms = "windowManagement.rooms"
    case windowManagementCommands = "windowManagement.commands"
    case clipboardEnabled = "clipboard.enabled"
    case clipboardRetention = "clipboard.retentionDays"
    case clipboardDefaultAction = "clipboard.defaultAction"
    case clipboardDisabledApps = "clipboard.disabledApps"
    case clipboardCommands = "clipboard.commands"
    case emojiSkinTone = "emoji.skinTone"
    case emojiGridColumns = "emoji.gridColumns"
    case emojiCommands = "emoji.commands"
    case calendarShowInLauncher = "calendar.showInLauncher"
    case calendarLauncherLimit = "calendar.launcherLimit"
    case calendarSpan = "calendar.span"
    case joinWindowMinutes = "calendar.joinWindowMinutes"
    case autoJoinConfirms = "calendar.autoJoinConfirms"
    case autoJoinNamedProvidersOnly = "calendar.autoJoinNamedProvidersOnly"
    case meetingBrowser = "calendar.meetingBrowser"
    case calendarMenuBarDisplay = "calendar.menuBar"
    case menuBarEvents = "calendar.menuBarUpcomingEvents"
    case menuBarLinkedEventsOnly = "calendar.menuBarLinkedEventsOnly"
    case calendarMenuBarHidesWhenEmpty = "calendar.menuBarHidesWhenEmpty"
    case hideCurrentEvent = "calendar.hideCurrentEventAfterMinutes"
    case calendarCommands = "calendar.commands"
    case extensionsShowInLauncher = "extensions.showInLauncher"

    /// 该键所在的顶层对象（section）。
    var section: String { String(rawValue.prefix { $0 != "." }) }

    /// 该键在其 section 内的名称。
    var name: String { String(rawValue.drop { $0 != "." }.dropFirst()) }

    /// 所有 section，按文件顺序排列。
    static let sections: [String] = allCases.reduce(into: []) { sections, key in
        if sections.last != key.section { sections.append(key.section) }
    }
}
